import {
  faAlignLeft,
  faArrowDown,
  faArrowUp,
  faArrowsRotate,
  faBook,
  faChevronDown,
  faCircleCheck,
  faCircleQuestion,
  faClone,
  faCode,
  faCodeBranch,
  faCopy,
  faDiagramProject,
  faDownload,
  faExpand,
  faFile,
  faFileCode,
  faFileImage,
  faFloppyDisk,
  faFolderOpen,
  faHeading,
  faKeyboard,
  faMagnifyingGlassMinus,
  faMagnifyingGlassPlus,
  faMinus,
  faPaste,
  faPlus,
  faRepeat,
  faRightFromBracket,
  faRotate,
  faRotateLeft,
  faRotateRight,
  faScissors,
  faSitemap,
  faSliders,
  faTerminal,
  faTrashCan,
  faTriangleExclamation,
  faWandMagicSparkles,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';
import { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import { BlockKind } from './model/diagram.model';

export const ICONS = {
  logo: faDiagramProject,
  newFile: faFile,
  open: faFolderOpen,
  save: faFloppyDisk,
  undo: faRotateLeft,
  redo: faRotateRight,
  cut: faScissors,
  copy: faCopy,
  paste: faPaste,
  duplicate: faClone,
  delete: faTrashCan,
  up: faArrowUp,
  down: faArrowDown,
  png: faFileImage,
  svg: faFileCode,
  download: faDownload,
  zoomIn: faMagnifyingGlassPlus,
  zoomOut: faMagnifyingGlassMinus,
  fit: faExpand,
  help: faCircleQuestion,
  inspector: faSliders,
  terminal: faTerminal,
  warning: faTriangleExclamation,
  ok: faCircleCheck,
  plus: faPlus,
  minus: faMinus,
  close: faXmark,
  chevron: faChevronDown,
  sample: faWandMagicSparkles,
  book: faBook,
  keyboard: faKeyboard,
  title: faHeading,
} satisfies Record<string, IconDefinition>;

export const BLOCK_ICONS: Record<BlockKind, IconDefinition> = {
  statement: faAlignLeft,
  call: faCode,
  exit: faRightFromBracket,
  if: faCodeBranch,
  switch: faSitemap,
  while: faRotate,
  doWhile: faArrowsRotate,
  for: faRepeat,
};
